spring:
  datasource:
    url: jdbc:h2:mem:credit_application_system_db;DB_CLOSE_DELAY=-1
    username: dev
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    hibernate:
      properties:
        hibernate.format_sql=true
    show-sql: true

springdoc:
  swagger-ui:
    path:/swagger-ui.html
